development:
  adapter: postgresql
  database: courses_development
  username: masonfoxmatthews
  password:
  host: localhost

test:
  adapter: postgresql
  database: courses_test
  username: masonfoxmatthews
  password:
  host: localhost

production:
  adapter: postgresql
  database: courses_production
  username: masonfoxmatthews
  password:
  host: localhost
